## Project Description

In this project, I worked with real-world music streaming data to explore and analyze listening habits among users from two cities: Springfield and Shelbyville.

The main objective was to clean, organize, and examine the dataset to identify patterns in user behavior, compare music preferences between cities, and evaluate how listening activity varies across different days and times. Using Python, the data was processed and analyzed to generate insights that support data-driven conclusions about user engagement and music consumption trends.

Through this project, I applied fundamental data analysis techniques, including data cleaning, filtering, aggregation, and exploratory data analysis (EDA), while developing practical skills in working with real-world datasets.

In [ ]:
# Step 1.1. Import libraries.
import pandas as pd

In [2]:
# Etapa 1.2. Lee el archivo music_project_en.csv de la carpeta /datasets/ y guárdalo en la variable df:

df = pd.read_csv('music_project_en.csv')

In [3]:
# Etapa 1.3. Muestra las 10 primeras filas de la tabla:
df.head(10)

,userID,Track,artist,genre,City,time,Day
0,FFB692EC,Kamigata To Boots,The Mass Missile,rock,Shelbyville,20:28:33,Wednesday
1,55204538,Delayed Because of Accident,Andreas Rönnberg,rock,Springfield,14:07:09,Friday
2,20EC38,Funiculì funiculà,Mario Lanza,pop,Shelbyville,20:58:07,Wednesday
3,A3DD03C9,Dragons in the Sunset,Fire + Ice,folk,Shelbyville,08:37:09,Monday
4,E2DC1FAE,Soul People,Space Echo,dance,Springfield,08:34:34,Monday
5,842029A1,Chains,Obladaet,rusrap,Shelbyville,13:09:41,Friday
6,4CB90AA5,True,Roman Messer,dance,Springfield,13:00:07,Wednesday
7,F03E1C1F,Feeling This Way,Polina Griffith,dance,Springfield,20:47:49,Wednesday
8,8FA1D3BE,L’estate,Julia Dalia,ruspop,Springfield,09:17:40,Friday
9,E772D5C0,Pessimist,NaN,dance,Shelbyville,21:20:49,Wednesday

In [4]:
# Etapa 1.4. Obtén la información general sobre la tabla con el método info().
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65079 entries, 0 to 65078
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0     userID  65079 non-null  object
 1   Track     63736 non-null  object
 2   artist    57512 non-null  object
 3   genre     63881 non-null  object
 4     City    65079 non-null  object
 5   time      65079 non-null  object
 6   Day       65079 non-null  object
dtypes: object(7)
memory usage: 3.5+ MB

Escribe algunas observaciones por tu parte. Contesta a las siguientes preguntas: ¶
1.   ¿Qué tipo de datos hay en las filas? ¿Cómo podemos saber qué almacenan las columnas?
todos los tipos de datos son "object", y para saber que almacenan las columnas con el metodo .head()
2.   ¿Hay suficientes datos para proporcionar respuestas a nuestra hipótesis o necesitamos más información?
Tenemos 3 columnas (Track, artist, genre) con valores ausentes. necesitamos analizar mas la informacion para saber si tenemos suficientes datos para proporcionar respuestas.
3.   ¿Notaste algún problema en los datos, como valores ausentes, duplicados o tipos de datos incorrectos?

Etapa 2. Preprocesamiento de los datos 
Tu objetivo aquí es preparar los datos para analizarlos. El primer paso es resolver los problemas con los encabezados. Después podemos avanzar a los valores ausentes y duplicados. ¡Empecemos!

Vamos a corregir el formato en los encabezados de la tabla.

In [5]:
# 2.1. Estilo del encabezado 
# Etapa 2.1. Muestra los encabezados de la tabla (los nombres de las columnas):

df.columns

Index(['  userID', 'Track', 'artist', 'genre', '  City  ', 'time', 'Day'], dtype='object')

Vamos cambiar los encabezados de la tabla siguiendo las reglas estilísticas convencionales:

Todos los caracteres deben ser minúsculas.
Elimina los espacios.
Si el nombre tiene varias palabras, utiliza snake_case, es decir, añade un guion bajo ( _ ) entre las palabras en lugar de un espacio.

Etapa 2.2. Utiliza el bucle for para iterar sobre los nombres de las columnas y poner todos los caracteres en minúsculas. Cuando hayas terminado, vuelve a mostrar los encabezados de la tabla:

Etapa 2.3. Ahora, utilizando el mismo método, elimina los espacios al principio y al final de los nombres de las columnas y muestra los nombres de las columnas de nuevo:

In [8]:
nuevas_columnas = []

for columna in df.columns:
    
    nueva_columna = columna.strip() # 2.3 Eliminar los espacios
    nueva_columna = nueva_columna.lower() # 2.2 Todos los caracteres deben ser minúsculas
    nueva_columna = nueva_columna.replace(" ","_") #añade un guion bajo ( _ ) entre las palabras en lugar de un espacio.

    nuevas_columnas.append(nueva_columna)

df.columns = nuevas_columnas

In [11]:
# Etapa 2.4. Necesitamos aplicar la regla de snake_case en la columna userid. Debe ser user_id. Cambia el nombre de esta columna y muestra los nombres de todas las columnas cuando hayas terminado.

df.rename(columns={'userid': 'user_id'}, inplace=True)

In [14]:
# Etapa 2.5. Comprueba el resultado. Muestra los encabezados una vez más:
df.columns

Index(['user_id', 'track', 'artist', 'genre', 'city', 'time', 'day'], dtype='object')

2.2. Valores ausentes 
Etapa 2.5. Primero, encuentra el número de valores ausentes en la tabla. Debes utilizar dos métodos para obtener el número de valores ausentes.

In [19]:
# Valores Ausentes
df.isna().sum().sort_values(ascending=False).reset_index()

     index     0
0   artist  7567
1    track  1343
2    genre  1198
3  user_id     0
4     city     0
5     time     0
6      day     0

Etapa 2.6. Sustituye los valores ausentes en las columnas 'track', 'artist' y 'genre' con el string 'unknown'.

Crea una lista llamada columns_to_replace que contenga los nombres de las columnas 'track', 'artist' y 'genre'.

Usa un bucle for para iterar sobre cada columna en columns_to_replace.

Dentro del bucle, sustituye los valores ausentes en cada columna con el string 'unknown'

In [20]:
# Crea una lista llamada columns_to_replace que contenga los nombres de las columnas 'track', 'artist' y 'genre'.

columns_to_replace = ['track', 'artist', 'genre']

In [22]:
# Usa un bucle for para iterar sobre cada columna en columns_to_replace.

for columna in columns_to_replace:
    df[columna] = df[columna].fillna('unknown')

In [24]:
# Etapa 2.7. Ahora comprueba el resultado para asegurarte de que no falten valores ausentes por reemplazar en el conjunto de datos. Para ello, cuenta los valores ausentes una vez más.
df.isna().sum().sort_values(ascending=False).reset_index()

     index  0
0  user_id  0
1    track  0
2   artist  0
3    genre  0
4     city  0
5     time  0
6      day  0

2.3. Duplicados 
Etapa 2.8. Encuentra el número de duplicados explícitos en la tabla. Una vez más, debes aplicar dos métodos para obtener la cantidad de duplicados explícitos.

In [27]:
# Valores Duplicados

df.duplicated().sum()

np.int64(3826)

In [28]:
# Etapa 2.9. Ahora, elimina todos los duplicados. Para ello, llama al método que hace exactamente esto.

df = df.drop_duplicates()

In [29]:
df.duplicated().sum()

np.int64(0)

Ahora queremos deshacernos de los duplicados implícitos en la columna genre. Por ejemplo, el nombre de un género se puede escribir de varias formas. Dichos errores también pueden afectar al resultado.

Etapa 2.11. Primero debemos mostrar una lista de nombres de géneros únicos, por orden alfabético. Para ello:

Extrae la columna genre del DataFrame.
Llama al método que devolverá todos los valores únicos en la columna extraída.

In [ ]:
df['genre'].unique() # Metodo Unique devolvera todos los valores unicos en la columna genre

array(['rock', 'pop', 'folk', 'dance', 'rusrap', 'ruspop', 'world',
       'electronic', 'unknown', 'alternative', 'children', 'rnb', 'hip',
       'jazz', 'postrock', 'latin', 'classical', 'metal', 'reggae',
       'triphop', 'blues', 'instrumental', 'rusrock', 'dnb', 'türk',
       'post', 'country', 'psychedelic', 'conjazz', 'indie',
       'posthardcore', 'local', 'avantgarde', 'punk', 'videogame',
       'techno', 'house', 'christmas', 'melodic', 'caucasian',
       'reggaeton', 'soundtrack', 'singer', 'ska', 'salsa', 'ambient',
       'film', 'western', 'rap', 'beats', "hard'n'heavy", 'progmetal',
       'minimal', 'tropical', 'contemporary', 'new', 'soul', 'holiday',
       'german', 'jpop', 'spiritual', 'urban', 'gospel', 'nujazz',
       'folkmetal', 'trance', 'miscellaneous', 'anime', 'hardcore',
       'progressive', 'korean', 'numetal', 'vocal', 'estrada', 'tango',
       'loungeelectronic', 'classicmetal', 'dubstep', 'club', 'deep',
       'southern', 'black', 'folkrock', 'fitness', 'french', 'disco',
       'religious', 'hiphop', 'drum', 'extrememetal', 'türkçe',
       'experimental', 'easy', 'metalcore', 'modern', 'argentinetango',
       'old', 'swing', 'breaks', 'eurofolk', 'stonerrock', 'industrial',
       'funk', 'middle', 'variété', 'other', 'adult', 'christian',
       'thrash', 'gothic', 'international', 'muslim', 'relax', 'schlager',
       'caribbean', 'nu', 'breakbeat', 'comedy', 'chill', 'newage',
       'specialty', 'uzbek', 'k-pop', 'balkan', 'chinese', 'meditative',
       'dub', 'power', 'death', 'grime', 'arabesk', 'romance', 'flamenco',
       'leftfield', 'european', 'tech', 'newwave', 'dancehall', 'mpb',
       'piano', 'top', 'bigroom', 'opera', 'celtic', 'tradjazz',
       'acoustic', 'epicmetal', 'hip-hop', 'historisch', 'downbeat',
       'downtempo', 'africa', 'audiobook', 'jewish', 'sängerportrait',
       'deutschrock', 'eastern', 'action', 'future', 'electropop',
       'folklore', 'bollywood', 'marschmusik', 'rnr', 'karaoke', 'indian',
       'rancheras', 'afrikaans', 'rhythm', 'sound', 'deutschspr', 'trip',
       'lovers', 'choral', 'dancepop', 'retro', 'smooth', 'mexican',
       'brazilian', 'ïîï', 'mood', 'surf', 'gangsta', 'inspirational',
       'idm', 'ethnic', 'bluegrass', 'broadway', 'animated', 'americana',
       'karadeniz', 'rockabilly', 'colombian', 'self', 'hop', 'sertanejo',
       'japanese', 'canzone', 'lounge', 'sport', 'ragga', 'traditional',
       'gitarre', 'frankreich', 'emo', 'laiko', 'cantopop', 'glitch',
       'documentary', 'oceania', 'popeurodance', 'dark', 'vi', 'grunge',
       'hardstyle', 'samba', 'garage', 'art', 'folktronica', 'entehno',
       'mediterranean', 'chamber', 'cuban', 'taraftar', 'gypsy',
       'hardtechno', 'shoegazing', 'bossa', 'latino', 'worldbeat',
       'malaysian', 'baile', 'ghazal', 'arabic', 'popelectronic', 'acid',
       'kayokyoku', 'neoklassik', 'tribal', 'tanzorchester', 'native',
       'independent', 'cantautori', 'handsup', 'punjabi', 'synthpop',
       'rave', 'französisch', 'quebecois', 'speech', 'soulful', 'jam',
       'ram', 'horror', 'orchestral', 'neue', 'roots', 'slow', 'jungle',
       'indipop', 'axé', 'fado', 'showtunes', 'arena', 'irish',
       'mandopop', 'forró', 'dirty', 'regional'], dtype=object)

Etapa 2.12. Vamos a examinar la lista para identificar duplicados implícitos del género hiphop, es decir, nombres mal escritos o variantes que hacen referencia al mismo género musical.

Los duplicados que encontrarás son:

hip
hop
hip-hop
Para solucionarlo, vamos a crear una función llamada replace_wrong_values()

Define una función llamada replace_wrong_values() que reciba los siguientes parámetros:
df: el DataFrame a modificar
column: el nombre de la columna a trabajar
wrong_values: una lista con los valores incorrectos
correct_value: el valor correcto para reemplazar
Dentro de la función, usa un bucle for para iterar sobre cada valor incorrecto y aplicar .replace().

In [32]:
def replace_wrong_values(df, column, wrong_values, correct_value):
    for wrong in wrong_values:
        df[column] = df[column].replace(wrong, correct_value)

Etapa 2.13. Ahora, llama a la función pasando:

df como el DataFrame
'genre' como nombre de columna
['hip', 'hop', 'hip-hop'] como lista de valores incorrectos
'hiphop' como valor correcto

In [33]:
replace_wrong_values(df, 'genre', ['hip', 'hop', 'hip-hop'], 'hiphop')

C:\Users\Crist\AppData\Local\Temp\ipykernel_59724\3359571112.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column] = df[column].replace(wrong, correct_value)

In [36]:
df['genre'].unique()

array(['rock', 'pop', 'folk', 'dance', 'rusrap', 'ruspop', 'world',
       'electronic', 'unknown', 'alternative', 'children', 'rnb',
       'hiphop', 'jazz', 'postrock', 'latin', 'classical', 'metal',
       'reggae', 'triphop', 'blues', 'instrumental', 'rusrock', 'dnb',
       'türk', 'post', 'country', 'psychedelic', 'conjazz', 'indie',
       'posthardcore', 'local', 'avantgarde', 'punk', 'videogame',
       'techno', 'house', 'christmas', 'melodic', 'caucasian',
       'reggaeton', 'soundtrack', 'singer', 'ska', 'salsa', 'ambient',
       'film', 'western', 'rap', 'beats', "hard'n'heavy", 'progmetal',
       'minimal', 'tropical', 'contemporary', 'new', 'soul', 'holiday',
       'german', 'jpop', 'spiritual', 'urban', 'gospel', 'nujazz',
       'folkmetal', 'trance', 'miscellaneous', 'anime', 'hardcore',
       'progressive', 'korean', 'numetal', 'vocal', 'estrada', 'tango',
       'loungeelectronic', 'classicmetal', 'dubstep', 'club', 'deep',
       'southern', 'black', 'folkrock', 'fitness', 'french', 'disco',
       'religious', 'drum', 'extrememetal', 'türkçe', 'experimental',
       'easy', 'metalcore', 'modern', 'argentinetango', 'old', 'swing',
       'breaks', 'eurofolk', 'stonerrock', 'industrial', 'funk', 'middle',
       'variété', 'other', 'adult', 'christian', 'thrash', 'gothic',
       'international', 'muslim', 'relax', 'schlager', 'caribbean', 'nu',
       'breakbeat', 'comedy', 'chill', 'newage', 'specialty', 'uzbek',
       'k-pop', 'balkan', 'chinese', 'meditative', 'dub', 'power',
       'death', 'grime', 'arabesk', 'romance', 'flamenco', 'leftfield',
       'european', 'tech', 'newwave', 'dancehall', 'mpb', 'piano', 'top',
       'bigroom', 'opera', 'celtic', 'tradjazz', 'acoustic', 'epicmetal',
       'historisch', 'downbeat', 'downtempo', 'africa', 'audiobook',
       'jewish', 'sängerportrait', 'deutschrock', 'eastern', 'action',
       'future', 'electropop', 'folklore', 'bollywood', 'marschmusik',
       'rnr', 'karaoke', 'indian', 'rancheras', 'afrikaans', 'rhythm',
       'sound', 'deutschspr', 'trip', 'lovers', 'choral', 'dancepop',
       'retro', 'smooth', 'mexican', 'brazilian', 'ïîï', 'mood', 'surf',
       'gangsta', 'inspirational', 'idm', 'ethnic', 'bluegrass',
       'broadway', 'animated', 'americana', 'karadeniz', 'rockabilly',
       'colombian', 'self', 'sertanejo', 'japanese', 'canzone', 'lounge',
       'sport', 'ragga', 'traditional', 'gitarre', 'frankreich', 'emo',
       'laiko', 'cantopop', 'glitch', 'documentary', 'oceania',
       'popeurodance', 'dark', 'vi', 'grunge', 'hardstyle', 'samba',
       'garage', 'art', 'folktronica', 'entehno', 'mediterranean',
       'chamber', 'cuban', 'taraftar', 'gypsy', 'hardtechno',
       'shoegazing', 'bossa', 'latino', 'worldbeat', 'malaysian', 'baile',
       'ghazal', 'arabic', 'popelectronic', 'acid', 'kayokyoku',
       'neoklassik', 'tribal', 'tanzorchester', 'native', 'independent',
       'cantautori', 'handsup', 'punjabi', 'synthpop', 'rave',
       'französisch', 'quebecois', 'speech', 'soulful', 'jam', 'ram',
       'horror', 'orchestral', 'neue', 'roots', 'slow', 'jungle',
       'indipop', 'axé', 'fado', 'showtunes', 'arena', 'irish',
       'mandopop', 'forró', 'dirty', 'regional'], dtype=object)

3. Etapa 3. Análisis
3.1. Tarea: Comparar el comportamiento de los usuarios en las dos ciudades 
Queremos analizar si hay diferencias en la cantidad de canciones reproducidas en Springfield y Shelbyville. Para ello, usaremos los datos de dos días de la semana: lunes y viernes.

Compararemos cuántas canciones se escucharon en cada ciudad durante esos días para identificar posibles patrones de comportamiento.

Sigue estos tres pasos para organizar tu análisis:

Dividir: agrupa los datos por ciudad.

Aplicar: cuenta cuántas canciones se reproducen en cada grupo.

Combinar: presenta los resultados de forma que se puedan comparar fácilmente ambas ciudades.

Repite este proceso por separado para cada uno de los dos días.

In [ ]:
agrupa los datos por ciudad.

In [40]:
df.groupby('city')['track'].count()

city
Shelbyville    18512
Springfield    42741
Name: track, dtype: int64

Etapa 3.2. Redacta brevemente tus observaciones sobre los resultados.

¿Qué diferencias encontraste entre Springfield y Shelbyville? ¿A qué podrían deberse?
La diferencia que veo es que Springfield tiene mas reproducciones de canciones que shelbyville

Etapa 3.2. Redacta brevemente tus observaciones sobre los resultados.

¿Qué diferencias encontraste entre Springfield y Shelbyville? ¿A qué podrían deberse?

In [49]:
df_dias = df[df['day'].isin(['Monday','Friday'])]

In [51]:
df_dias.columns

Index(['user_id', 'track', 'artist', 'genre', 'city', 'time', 'day'], dtype='object')

In [52]:
df_dias.groupby('day')['track'].count()

day
Friday    21840
Monday    21354
Name: track, dtype: int64

Etapa 3.4. Describe brevemente qué observaste al comparar los lunes y viernes.

¿Hubo un día con más actividad? ¿Cambia algo si analizas cada ciudad por separado?
el dia viernes tiene mas reproducciones, con esto indica que los usuarios tienden a escuchar musica acercandose el fin de semana

Etapa 3.5

Ahora vamos a combinar dos criterios: día y ciudad.

Crea una función llamada number_tracks() que reciba dos parámetros:

day: un día de la semana (por ejemplo, 'Monday')
city: el nombre de una ciudad (por ejemplo, 'Springfield')
Dentro de la función:

Filtra el DataFrame por el día.
Luego, filtra por la ciudad.
Cuenta cuántas veces aparece 'user_id' en ese filtro.
Devuelve ese número como resultado.

In [53]:
def number_tracks(day, city):
    # Almacena las filas donde el valor en 'day' es igual al parámetro day
    day_data = df[df['day'] == day]
    
    # Filtra las filas donde el valor en 'city' es igual al parámetro city
    city_data = day_data[day_data['city'] == city]
    
    # Extrae la columna 'user_id' y aplica el método count()
    track_count = city_data['user_id'].count()
    
    # Devuelve el número de valores de la columna 'user_id'
    return track_count

In [55]:
# El número de canciones reproducidas en Springfield el lunes
springfield_lunes = number_tracks('Monday', 'Springfield')
print("Springfield el lunes:", springfield_lunes)

Springfield el lunes: 15740

In [57]:
# El número de canciones reproducidas en Shelbyville el lunes
shelbyville_lunes = number_tracks('Monday', 'Shelbyville')
print("Shelbyville el lunes:", shelbyville_lunes)

Shelbyville el lunes: 5614

In [58]:
# El número de canciones reproducidas en Springfield el viernes
springfield_viernes = number_tracks('Friday', 'Springfield')
print("Springfield el viernes:", springfield_viernes)

Springfield el viernes: 15945

In [59]:
# El número de canciones reproducidas en Shelbyville el viernes
shelbyville_viernes = number_tracks('Friday', 'Shelbyville')
print("Shelbyville el viernes:", shelbyville_viernes)

Shelbyville el viernes: 5895

1. Escribe tus conclusiones finales sobre el análisis
Redacta un resumen breve y claro de los hallazgos obtenidos durante el proceso de análisis. Tu conclusión debe:

Mencionar los principales patrones que observaste en los datos.
Identificar cualquier problema encontrado y cómo lo solucionaste.
Explicar cómo estas acciones ayudaron a mejorar la calidad del análisis.
Reflexiona también sobre la pregunta central:

¿Los datos muestran que el comportamiento de los usuarios —en cuanto a la música que escuchan— varía según la ciudad y el día de la semana?

Apoya tu respuesta con ejemplos concretos de los resultados obtenidos.